name: Build Windows Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install PyInstaller
        run: pip install pyinstaller urllib3

      - name: Build executable
        run: pyinstaller --onefile --noconsole --icon NONE pythonw.py

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest  # Specify your version tag
          files: dist/pythonw.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
